In [13]:
print("python is working")

python is working

In [14]:
import pandas as pd 

df=pd.read_excel("C:/Users/sriya parichi/Downloads/customer_shopping_behavior_updated.xlsx")

In [15]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13900 entries, 0 to 13899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             13900 non-null  int64
 1   Age                     13900 non-null  int64
 2   Gender                  13900 non-null  object
 3   Item Purchased          13900 non-null  object
 4   Category                13900 non-null  object
 5   Purchase Amount (USD)   13900 non-null  int64
 6   Location                13900 non-null  object
 7   Size                    13900 non-null  object
 8   Color                   13900 non-null  object
 9   Season                  13900 non-null  object
 10  Review Rating           13863 non-null  float64
 11  Subscription Status     13900 non-null  object
 12  Shipping Type           13900 non-null  object
 13  Discount Applied        13900 non-null  object
 14  Promo Code Used         13900 non-null  object
 15  Previous Purchases      13900 non-null  int64
 16  Payment Method          13900 non-null  object
 17  Frequency of Purchases  13900 non-null  object
dtypes: float64(1), int64(4), object(13)
memory usage: 1.9+ MB

In [16]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,13900.000000,13900.000000,13900,13900,13900,13900.000000,13900,13900,13900,13900,13863.000000,13900,13900,13900,13900,13900.000000,13900,13900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Jewelry,Clothing,NaN,Montana,M,Green,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,9417,616,6286,NaN,357,6213,635,3631,NaN,10195,2436,7919,7963,NaN,2461,2063
mean,6950.500000,43.963525,NaN,NaN,NaN,60.110144,NaN,NaN,NaN,NaN,3.744395,NaN,NaN,NaN,NaN,25.371583,NaN,NaN
std,4012.728706,15.319450,NaN,NaN,NaN,23.370797,NaN,NaN,NaN,NaN,0.719974,NaN,NaN,NaN,NaN,14.450781,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,3475.750000,31.000000,NaN,NaN,NaN,40.000000,NaN,NaN,NaN,NaN,3.110684,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,6950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.744703,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,10425.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.373545,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,13900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [17]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [18]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [19]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [20]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [22]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [23]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [24]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [25]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [26]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [27]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [28]:
(df['discount_applied'] == df['promo_code_used']).all()

False

In [29]:
df = df.drop('promo_code_used', axis=1)

In [30]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [31]:
pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\sriya parichi\anaconda3\anaconda\anaconda\lib\site-packages (4.0.32)
Requirement already satisfied: sqlalchemy in c:\users\sriya parichi\anaconda3\anaconda\anaconda\lib\site-packages (1.4.32)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\sriya parichi\anaconda3\anaconda\anaconda\lib\site-packages (from sqlalchemy) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [33]:
import pyodbc

print(pyodbc.drivers())

['SQL Server', 'SQL Server Native Client RDA 11.0', 'ODBC Driver 17 for SQL Server', 'ODBC Driver 18 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [34]:
import pyodbc

conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=LAPTOP-OGVI9M46\SRIYAPARICHA;"
    r"DATABASE=customer_analysis;"
    r"Trusted_Connection=yes;"
)

print("Connected successfully!")

Connected successfully!

In [35]:
cursor = conn.cursor()

cursor.execute("SELECT DB_NAME()")

print(cursor.fetchone())

('customer_analysis', )

In [37]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

connection_string = quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=LAPTOP-OGVI9M46\\SRIYAPARICHA;"
    "DATABASE=customer_analysis;"
    "Trusted_Connection=yes;"
)

engine = create_engine(
    "mssql+pyodbc:///?odbc_connect=" + connection_string
)

print("SQLAlchemy engine created successfully!")

SQLAlchemy engine created successfully!

In [38]:
query = """
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
"""

tables = pd.read_sql(query, engine)
tables

Empty DataFrame
Columns: [TABLE_NAME]
Index: []

In [39]:
df.to_sql(
    "customer_behavior",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data uploaded successfully!")

Data uploaded successfully!